import remote_remote

r = remote(2)
r.on()
r.bounce_off()
r.press(address=r.P13,duration=10)
r.wait()
r.press(address=r.E1_S,duration=10)
r.wait()
r.turn(address=r.E2,ticks=2,duration=10)
r.wait()
r.press(address=r.E1_S,duration=12)
r.wait()
r.turn(address=r.E2,ticks=3,duration=12)
r.press(address=r.P13,duration=10)
r.reset()
r.loadseed()
r.press(address=r.P13,duration=10)
r.wait()
r.press(address=r.E1_S,duration=10)
r.wait()
r.turn(address=r.E2,ticks=2,duration=10)
r.off()